package com.accantosystems.stratoss.driver.ucd.model.resourcemanager;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel
@JsonInclude(value=JsonInclude.Include.NON_EMPTY, content=JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown=true)
public class InternalResourceInstance {

	@ApiModelProperty(position=1, example="3cb7822b-fc44-46ab-8072-9c65cd778d1f", value="Unique identifier for the internal resource, as generated by the Resource Manager or underlying infrastructure")
	private String id;
	@ApiModelProperty(position=2, example="MGMT-NETWORK", value="Human-readable (non-unique) name given to the internal resource by the Resource Manager or underlying infrastructure")
	private String name;
	@ApiModelProperty(position=3, example="OpenDaylight::PrivateNetwork", value="Type identifier for this internal resource")
	private String type;
	
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getType() {
		return type;
	}
	public void setType(String type) {
		this.type = type;
	}
	
}
