package com.accantosystems.stratoss.driver.ucd.model.resourcemanager;

import java.time.OffsetDateTime;
import java.util.Map;
import java.util.TreeMap;

import com.accantosystems.stratoss.driver.ucd.model.resourcemanager.TransitionStatus.State;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel
@JsonInclude(value=JsonInclude.Include.NON_EMPTY, content=JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown=true)
public class TransitionRequest {

	@ApiModelProperty(position=1, example="80fc4a66-7e92-41f8-b4bb-7cb98193f5fa", required=false, value="UUID generated by the Resource Manager for this request")
	private String requestId;
	@ApiModelProperty(position=2, example="default-rm::dev", required=false, value="Optional id used to uniquely identify the Resource Manager instance")
	private String resourceManagerId;
	@ApiModelProperty(position=3, example="dev-cloud", value="Unique identifier for the specific deployment location referenced in this request")
	private String deploymentLocation;
	@ApiModelProperty(position=4, example="default-rm::Resource::Network", value="Type identifier for this resource")
	private String resourceType;
	@ApiModelProperty(position=5, example="Transition::Start", value="Name of the requested transition/operation to be performed by the Resource Manager")
	private String transitionName;
	@ApiModelProperty(position=6, example="default-rm://c675e0bd-9c6c-43ca-84bf-2c061d439c6b", required=false, value="Unique identifier for the resource, as generated by the Resource Manager")
	private String resourceId;
	@ApiModelProperty(position=7, example="dev-network", required=false, value="Human-readable (unique) name given to the resource by the Lifecycle Manager")
	private String resourceName;
	@ApiModelProperty(position=8, value="Key/value pairs for the properties of the relevant resource")
	private final Map<String, String> properties = new TreeMap<>();
	@ApiModelProperty(position=9, required=false, value="Optional additional key/value pairs for contextual information about the request")
	private final Map<String, String> context = new TreeMap<>();
	@ApiModelProperty(position=10, example="FAILED", required=false, value="Enumerated value indicating the current state of this request")
	private State requestState;
	@ApiModelProperty(position=11, example="Transition timed out after 600 seconds", required=false, value="Optional string to give more information as to the current state of this request, e.g. to indicate what error has occurred in failure scenarios")
	private String requestStateReason;
	@ApiModelProperty(position=12, required=false, value="Optional date and time this transition was started", example="2017-05-01T12:00:00Z")
	private OffsetDateTime startedAt;
	@ApiModelProperty(position=13, required=false, value="Optional date and time this transition was completed", example="2017-05-01T12:00:05Z")
	private OffsetDateTime finishedAt;
	
	public String getRequestId() {
		return requestId;
	}
	public void setRequestId(String requestId) {
		this.requestId = requestId;
	}
	public String getResourceManagerId() {
		return resourceManagerId;
	}
	public void setResourceManagerId(String resourceManagerId) {
		this.resourceManagerId = resourceManagerId;
	}
	public String getDeploymentLocation() {
		return deploymentLocation;
	}
	public void setDeploymentLocation(String deploymentLocation) {
		this.deploymentLocation = deploymentLocation;
	}
	public String getResourceType() {
		return resourceType;
	}
	public void setResourceType(String resourceType) {
		this.resourceType = resourceType;
	}
	public String getTransitionName() {
		return transitionName;
	}
	public void setTransitionName(String transitionName) {
		this.transitionName = transitionName;
	}
	public String getResourceId() {
		return resourceId;
	}
	public void setResourceId(String resourceId) {
		this.resourceId = resourceId;
	}
	public String getResourceName() {
		return resourceName;
	}
	public void setResourceName(String resourceName) {
		this.resourceName = resourceName;
	}
	public Map<String, String> getProperties() {
		return properties;
	}
	public Map<String, String> getContext() {
		return context;
	}
	public State getRequestState() {
		return requestState;
	}
	public void setRequestState(State requestState) {
		this.requestState = requestState;
	}
	public String getRequestStateReason() {
		return requestStateReason;
	}
	public void setRequestStateReason(String requestStateReason) {
		this.requestStateReason = requestStateReason;
	}
	public OffsetDateTime getStartedAt() {
		return startedAt;
	}
	public void setStartedAt(OffsetDateTime startedAt) {
		this.startedAt = startedAt;
	}
	public OffsetDateTime getFinishedAt() {
		return finishedAt;
	}
	public void setFinishedAt(OffsetDateTime finishedAt) {
		this.finishedAt = finishedAt;
	}
	
	@Override
	public String toString() {
		return String.format(
				"{\"_class\":\"TransitionRequest\", \"requestId\":\"%s\", \"resourceManagerId\":\"%s\", \"deploymentLocation\":\"%s\", \"resourceType\":\"%s\", \"transitionName\":\"%s\", \"resourceId\":\"%s\", \"resourceName\":\"%s\", \"properties\":%s, \"context\":%s, \"requestState\":\"%s\", \"requestStateReason\":\"%s\", \"startedAt\":\"%s\", \"finishedAt\":\"%s\"}",
				requestId, resourceManagerId, deploymentLocation, resourceType, transitionName, resourceId,
				resourceName, properties, context, requestState, requestStateReason, startedAt, finishedAt);
	}
	
}
