package com.accantosystems.stratoss.driver.ucd.model.resourcemanager;

import java.time.OffsetDateTime;
import java.util.Map;
import java.util.TreeMap;

import com.accantosystems.stratoss.driver.ucd.model.resourcemanager.TransitionStatus.State;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel
@JsonInclude(value=JsonInclude.Include.NON_EMPTY, content=JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown=true)
public class TransitionResponse {

	@ApiModelProperty(position=1, example="80fc4a66-7e92-41f8-b4bb-7cb98193f5fa", required=false, value="UUID generated by the Resource Manager for the request")
	private String requestId;
	@ApiModelProperty(position=2, example="UCD-dev", required=false, value="Optional id used to uniquely identify the Resource Manager instance sending this response")
	private String resourceManagerId;
	@ApiModelProperty(position=3, example="UCD:Cloud:MWC@DC1", value="Unique identifier for the specific deployment location referenced in the request")
	private String deploymentLocation;
	@ApiModelProperty(position=4, example="UCD::Blueprint::VideoStreamer::1.0", value="Type identifier for the resource")
	private String resourceType;
	@ApiModelProperty(position=5, example="Transition::Start", value="Name of the requested transition/operation performed by the Resource Manager")
	private String transitionName;
	@ApiModelProperty(position=6, value="Resource instance that was manipulated")
	private ResourceInstance resourceInstance;
	@ApiModelProperty(position=7, required=false, value="Optional additional key/value pairs for contextual information about the request")
	private final Map<String, String> context = new TreeMap<>();
	@ApiModelProperty(position=8, example="FAILED", required=false, value="Enumerated value indicating the current state of this transition or operation")
	private State requestState;
	@ApiModelProperty(position=9, example="Transition timed out after 600 seconds", required=false, value="Optional string to give more information as to the current state of this transition or operation, e.g. to indicate what error has occurred in failure scenarios")
	private String requestStateReason;
	@ApiModelProperty(position=10, required=false, value="Optional date and time this transition was started", example="2017-05-01T12:00:00Z")
	private OffsetDateTime startedAt;
	@ApiModelProperty(position=11, required=false, value="Optional date and time this transition was completed", example="2017-05-01T12:00:05Z")
	private OffsetDateTime finishedAt;
	
	public String getRequestId() {
		return requestId;
	}
	public void setRequestId(String requestId) {
		this.requestId = requestId;
	}
	public String getResourceManagerId() {
		return resourceManagerId;
	}
	public void setResourceManagerId(String resourceManagerId) {
		this.resourceManagerId = resourceManagerId;
	}
	public String getDeploymentLocation() {
		return deploymentLocation;
	}
	public void setDeploymentLocation(String deploymentLocation) {
		this.deploymentLocation = deploymentLocation;
	}
	public String getResourceType() {
		return resourceType;
	}
	public void setResourceType(String resourceType) {
		this.resourceType = resourceType;
	}
	public String getTransitionName() {
		return transitionName;
	}
	public void setTransitionName(String transitionName) {
		this.transitionName = transitionName;
	}
	public ResourceInstance getResourceInstance() {
		return resourceInstance;
	}
	public void setResourceInstance(ResourceInstance resourceInstance) {
		this.resourceInstance = resourceInstance;
	}
	public Map<String, String> getContext() {
		return context;
	}
	public State getRequestState() {
		return requestState;
	}
	public void setRequestState(State requestState) {
		this.requestState = requestState;
	}
	public String getRequestStateReason() {
		return requestStateReason;
	}
	public void setRequestStateReason(String requestStateReason) {
		this.requestStateReason = requestStateReason;
	}
	public OffsetDateTime getStartedAt() {
		return startedAt;
	}
	public void setStartedAt(OffsetDateTime startedAt) {
		this.startedAt = startedAt;
	}
	public OffsetDateTime getFinishedAt() {
		return finishedAt;
	}
	public void setFinishedAt(OffsetDateTime finishedAt) {
		this.finishedAt = finishedAt;
	}
	
}
